### ISSUE TITLE
Could you please help to upload the scene file?

### ISSUE THREAD

**Issue by mobyuan** [xinyangaa/Unity_URP_Genshin_Impact_Programmed_Skybox#1]
Hi, 
Could you please help to upload the scene file?
I have some issue when set up the material.
thanks a lot!!!

**Comment by xinyangaa** [comment]
The scene file is already in it. You can take a look at this article regarding material settings“ https://zhuanlan.zhihu.com/p/661658540 ”If there is anything you don't understand, you can ask me again
&nbsp;


1368030978
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月24日(星期二) 晚上7:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [xinyangaa/Unity_URP_Genshin_Impact_Programmed_Skybox] Could you please help to upload the scene file? (Issue #1)





 
Hi,
 Could you please help to upload the scene file?
 I have some issue when set up the material.
 thanks a lot!!!

**Comment by Iricia** [comment]
你好，项目中并没有场景文件，我也在设置Material时遇到了问题，想看下您的场景文件如何详细配置，多谢！

**Comment by xinyangaa** [comment]
Sorry for taking up your time, there should be scene files now

**Comment by mobyuan** [comment]
OH! Thanks a lot!
